# Stage 1: Build the application

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src/app
COPY ["SalahStreakApp.csproj", "./"]
RUN dotnet restore "SalahStreakApp.csproj"
COPY . .
RUN dotnet publish "SalahStreakApp.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Stage 2: Create the final runtime image

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "SalahStreakApp.dll"]